spring:
  application:
    name: Jersey REST Api
  # Profiles configuration
  profiles: [dev]
  profiles.active: dev
  # Data source configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/culu3
    username: culu3
    password: culu3
    driver-class-name: org.postgresql.Driver

# Hibernate JPA configuration
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
